### ISSUE TITLE
error happend in ruby3.1.2

### ISSUE THREAD

**Issue by jackli0855** [sampokuokkanen/is_my_sidekiq_ok#1]
error message:

> :in `setting': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/local/bundle/gems/dry-configurable-1.0.0/lib/dry/configurable/class_methods.rb:44:in `setting'
	from /usr/local/bundle/gems/is_my_sidekiq_ok-0.1.0/lib/is_my_sidekiq_ok.rb:13:in `<module:IsMySidekiqOk>'
	from /usr/local/bundle/gems/is_my_sidekiq_ok-0.1.0/lib/is_my_sidekiq_ok.rb:9:in `<main>'

**Comment by libao-np** [comment]
The ruby version is 3.1.2.  The Gemfile is like the following.
```
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.1.2'

gem 'rails', '6.1.7'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'e2mmap'
gem 'puma', '~> 6.0'
gem 'thwait'
gem 'sass-rails', '~> 6.0'
gem 'slack-notifier'
gem 'sprockets', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker'
gem 'bcrypt', '~> 3.1.7'
gem 'gon'
gem 'dead_end'
gem 'image_processing'

gem 'active_storage_validations'

gem 'bootsnap', '>= 1.1.0', require: false

gem 'paranoia', '2.4.3'
gem 'parallel'

gem 'settingslogic'
gem 'kaminari'
gem 'pagy'

gem 'active_model_serializers', '0.10.12'
gem 'data-confirm-modal', git: 'https://github.com/ifad/data-confirm-modal.git'
gem 'deep_cloneable', '~> 3.0.0'
gem 'render_async'
gem 'sidekiq'
gem 'sidekiq-batch'
gem 'rbtrace'
gem 'redis', '~> 4.0', '>= 4.0.2'
gem 'redis-rails'
gem 'stackprof', require: false
gem 'net-http-digest_auth', '~> 1.4', '>= 1.4.1'

gem 'chunky_png', '~> 1.3', '>= 1.3.5'
gem 'rqrcode', '~> 0.10.1'

gem 'aws-sdk'
gem 'aws-sdk-cloudfront', '=1.35.0'
gem 'aws-sdk-medialive', '~> 1.50'
gem 'aws-sdk-mediapackage', '~> 1.22'
gem 'aws-sdk-rails'
gem 'aws-sdk-s3', '1.48', require: false
gem 'http_accept_language'
gem 'moment_timezone-rails'

gem 'sidekiq-failures'
gem 'sidekiq-history'
gem 'is_my_sidekiq_ok'
gem 'sidekiq-scheduler'

gem 'm3u8'
gem 'jipcode'
gem 'rack-attack'
gem 'rack-timeout', require: 'rack/timeout/base'
gem 'distribute_reads'
gem 'exception_notification'
gem 'meta-tags', '2.14.0'

gem 'asset_sync'
gem 'fog-aws'

gem 'rails_material_design_icons'
gem 'whenever', require: false

gem 'newrelic_rpm'

gem 'dry-initializer', '~> 3.0'

gem 'action_policy'

gem 'browser'

gem 'restforce', '~> 5.0.4'
gem 'rubyzip'

gem 'charlock_holmes'

gem 'lograge', '0.11.2'

gem 'rswag-api'
gem 'rswag-ui'

gem 'hashids'

gem 'rest-client'

group :development, :staging, :uat do
  gem 'rack-dev-mark'
end

group :development, :staging, :test, :uat do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rails-env-credentials'
end
group :development, :uat do
  gem 'letter_opener'
  gem 'letter_opener_web', '~> 1.0'
end

group :development do
  gem 'meta_request'
  gem 'steep', require: false
  gem 'rbs', require: false
  gem 'rbs_rails', require: false
  gem "better_errors"
  gem "binding_of_caller"
  gem 'bullet'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '4.1.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'annotate', '3.1.1'
  gem 'brakeman'
  gem 'lefthook'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rails_best_practices'

  # Deployment gems
  gem 'capistrano', '~> 3.10', require: false
  gem 'capistrano3-puma'
  gem 'capistrano-linked-files'
  gem 'capistrano-nvm'
  gem 'capistrano-rails', '~> 1.4', require: false
  gem 'capistrano-rails-console', require: false
  gem 'capistrano-rbenv', '~> 2.1'
  gem 'capistrano-sidekiq'
  gem 'capistrano-yarn'
  gem 'lol_dba'
  gem 'rubocop'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'standard', group: %i[development test]

end

group :test do
  gem 'committee-rails'
  gem 'bullet'
  gem 'webmock'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 3.26'
  gem 'cuprite'
  gem 'rspec-html-matchers'
  gem 'simplecov', '~> 0.21.2', require: false
  gem 'simplecov-lcov', require: false
  gem 'site_prism'
  gem 'test-prof'

  gem 'rspec-html-matchers'
  gem 'action-cable-testing'
  gem 'rails-controller-testing'
  gem 'rspec-instafail', require: false
  gem 'rspec_junit_formatter'
  gem 'rspec-retry'
  gem 'rspec-sidekiq'
  gem 'simplecov-hashcov', git: 'https://github.com/sampokuokkanen/simplecov-hashcov.git', require: false
end

gem 'tzinfo-data', '1.2021.1'

# test framework
group :development, :test do
  gem 'database_cleaner'
  gem 'dead_end'
  gem 'factory_bot_rails', '~> 5.0.2'
  gem 'faker'
  gem 'rswag-specs'

  gem 'rspec-rails', '~> 5'
end

gem 'icalendar'

gem 'redis-namespace'
gem 'sitemap_generator'
gem 'wicked_pdf'
gem 'rails_warden', git: 'https://github.com/wardencommunity/rails_warden.git'
gem 'warden'

# vonage video api
gem 'opentok', '~> 4.3.0'

gem 'view_component'

```

**Comment by sampokuokkanen** [comment]
Thanks, I'll take a look.

**Comment by sampokuokkanen** [comment]
It's not Ruby, it's your dry-configurable version. I'll update the gem, but before that, you could downgrade your dry-configurable.

**Comment by sampokuokkanen** [comment]
Could you check the new version?

**Comment by sampokuokkanen** [comment]
Checked on Slack, probably ok now. Please write another issue if there are other problems.
